name: Publish to Pages
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Bundle script for production
        run: |
          rm -rf dist
          mkdir dist
          mkdir dist/public
          cp script.sh ./dist/public/index.html
      - name: Deploy script
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist/public --project-name=easy-devbox
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
